CREATE OR REPLACE 
FUNCTION SF_RETURN_MONTH
	(P_DT_REGISTER IN DATE)
RETURN VARCHAR2
IS
V_MONTH_REGISTER VARCHAR2(10);
V_DT_REGISTER_MONTH VARCHAR(2);
EXC_NOT_MONTH EXCEPTION;
BEGIN
	V_DT_REGISTER_MONTH := to_char(TRUNC(P_DT_REGISTER), 'mm');

	IF V_DT_REGISTER_MONTH = '01'
	THEN
		V_MONTH_REGISTER := 'JANEIRO';
	ELSIF V_DT_REGISTER_MONTH = '02'
	THEN 
		V_MONTH_REGISTER := 'FEVEREIRO';
	ELSIF V_DT_REGISTER_MONTH = '03'
	THEN
		V_MONTH_REGISTER := 'MARÇO';
	ELSIF V_DT_REGISTER_MONTH = '04'
	THEN
		V_MONTH_REGISTER := 'ABRIL';
	ELSIF V_DT_REGISTER_MONTH = '05'
	THEN
		V_MONTH_REGISTER := 'MAIO';
	ELSIF V_DT_REGISTER_MONTH = '06'
	THEN
		V_MONTH_REGISTER := 'JUNHO';
	ELSIF V_DT_REGISTER_MONTH = '07'
	THEN
		V_MONTH_REGISTER := 'JULHO';
	ELSIF V_DT_REGISTER_MONTH = '08'
	THEN
		V_MONTH_REGISTER := 'AGOSTO';
	ELSIF V_DT_REGISTER_MONTH = '09'
	THEN
		V_MONTH_REGISTER := 'SETEMBRO';
	ELSIF V_DT_REGISTER_MONTH = '10'
	THEN
		V_MONTH_REGISTER := 'OUTUBRO';
	ELSIF V_DT_REGISTER_MONTH = '11'
	THEN
		V_MONTH_REGISTER := 'NOVEMBRO';
	ELSIF V_DT_REGISTER_MONTH = '12'
	THEN
		V_MONTH_REGISTER := 'DEZEMBRO';
	ELSE
	 RAISE EXC_NOT_MONTH;
	END IF;
	RETURN V_MONTH_REGISTER;
END;

CREATE OR REPLACE 
PROCEDURE SP_INSERT_EXCEDEED_CALORIES
	(P_QT_CALORIES IN NUMBER, P_DT_REGISTER IN DATE)
AS
V_RQT_CALORIES_GOAL NUMBER(12,0);
V_QT_CALORIES_EXCEDEED NUMBER(12,0) := 0;
V_MONTH_REGISTER VARCHAR2(10);
BEGIN 
	V_MONTH_REGISTER := SF_RETURN_MONTH(P_DT_REGISTER);

	SELECT tmcg.QT_CALORIES_GOAL
	INTO V_RQT_CALORIES_GOAL
	FROM TB_MONTH_CALORIES_GOAL tmcg 
	WHERE tmcg.DS_MONTH = V_MONTH_REGISTER;

	IF P_QT_CALORIES > V_RQT_CALORIES_GOAL
	THEN 
		V_QT_CALORIES_EXCEDEED := P_QT_CALORIES - V_RQT_CALORIES_GOAL;
	
		INSERT INTO TB_DAILY_CALORIES_EXCEDEED
		(CD_DAILY_CAL_EXCEDEED, DT_REGISTER, QT_CALORIES)
		VALUES(SQ_DAILY_CAL_EXCEDEED.nextval, P_DT_REGISTER, 
		V_QT_CALORIES_EXCEDEED);
	END IF;
END;

BEGIN
	FOR V_DAILY_CALORIES_REGISTER IN (SELECT * FROM TB_DAILY_CALORIES) 
	LOOP
		SP_INSERT_EXCEDEED_CALORIES
				(V_DAILY_CALORIES_REGISTER.QT_CALORIES,
				V_DAILY_CALORIES_REGISTER.DT_REGISTER);
	END LOOP;
END;