CREATE OR REPLACE 
PROCEDURE SP_INSERT_EXCEDEED_CALORIES
	(P_QT_CALORIES IN NUMBER, P_DT_REGISTER IN DATE, P_CD_USER IN  NUMBER, P_CD_DAILY_CAL IN NUMBER)
AS
V_RQT_CALORIES_GOAL NUMBER(12,0);
V_QT_CALORIES_EXCEDEED NUMBER(12,0) := 0;
BEGIN 
	SELECT tmcg.QT_CALORIES_GOAL
	INTO V_RQT_CALORIES_GOAL
	FROM TB_MONTH_CALORIES_GOAL tmcg 
	WHERE tmcg.DS_MONTH = TRIM(TO_CHAR(TO_DATE('17/03/2025', 'dd/mm/yyyy'), 'MONTH'))
	AND tmcg.CD_USER = P_CD_USER;

	IF P_QT_CALORIES > V_RQT_CALORIES_GOAL
	THEN 
		V_QT_CALORIES_EXCEDEED := P_QT_CALORIES - V_RQT_CALORIES_GOAL;
	
		INSERT INTO TB_DAILY_CALORIES_EXCEDEED
		(CD_DAILY_CAL_EXCEDEED, DT_REGISTER, QT_CALORIES, CD_DAILY_CAL)
		VALUES(SQ_DAILY_CAL_EXCEDEED.nextval, P_DT_REGISTER, 
		V_QT_CALORIES_EXCEDEED, P_CD_DAILY_CAL);
	END IF;
	EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('error...');
        ROLLBACK;
	ROLLBACK;
END;

BEGIN
	FOR V_DAILY_CALORIES_REGISTER IN (SELECT * FROM TB_DAILY_CALORIES) 
	LOOP
		SP_INSERT_EXCEDEED_CALORIES
				(V_DAILY_CALORIES_REGISTER.QT_CALORIES,
				V_DAILY_CALORIES_REGISTER.DT_REGISTER, 
				V_DAILY_CALORIES_REGISTER.CD_USER,
				V_DAILY_CALORIES_REGISTER.CD_DAILY_CAL);
	END LOOP;
END;