--CRIAÇÃO DE TABELAS
CREATE TABLE TB_DAILY_CALORIES(
	CD_DAILY_CAL NUMBER(12, 0),
	DT_REGISTER DATE DEFAULT SYSDATE NOT NULL,
	QT_CALORIES NUMBER(12, 0) DEFAULT 0 NOT NULL,
	CONSTRAINT PK_TB_DAILY_CALORIES PRIMARY KEY(CD_DAILY_CAL)
);

ALTER TABLE TB_DAILY_CALORIES
ADD UNIQUE (DT_REGISTER);

CREATE TABLE TB_DAILY_EXERCISE(
    CD_DAILY_EXERCISE NUMBER(12, 0),
    DT_REGISTER DATE DEFAULT SYSDATE NOT NULL,
    VL_BURNED_CALORIES NUMBER(12, 0) DEFAULT 0, 
  	CONSTRAINT PK_TB_DAILY_EXERCISE PRIMARY KEY(CD_DAILY_EXERCISE)
);

CREATE TABLE TB_MONTH_CALORIES_GOAL(
    CD_MONTH_CAL_GOAL NUMBER(12, 0),
    DS_MONTH VARCHAR2(10) NOT NULL,
    QT_CALORIES_GOAL NUMBER(12, 0) DEFAULT 0 NOT NULL, 
    FL_ACTIVE NUMBER(12, 0) NOT NULL,
  	CONSTRAINT TB_MONTH_CALORIES_GOAL PRIMARY KEY(CD_MONTH_CAL_GOAL)
);

CREATE TABLE TB_DAILY_CALORIES_EXCEDEED(
	CD_DAILY_CAL_EXCEDEED NUMBER(12, 0),
	DT_REGISTER DATE NOT NULL,
	QT_CALORIES NUMBER(12, 0) DEFAULT 0 NOT NULL,
	CONSTRAINT PK_TB_DAILY_CALORIES_EXCEDEED PRIMARY KEY(CD_DAILY_CAL_EXCEDEED)
);

--CRIAÇÃO DE SEQUENCES
CREATE SEQUENCE SQ_CD_DAILY_CAL
      INCREMENT BY 1
      START WITH 1
      NOMAXVALUE
      NOCYCLE
      CACHE 10;

CREATE SEQUENCE SQ_DAILY_EXERCISE
      INCREMENT BY 1
      START WITH 1
      NOMAXVALUE
      NOCYCLE
      CACHE 10;

CREATE SEQUENCE SQ_MONTH_CAL_GOAL
      INCREMENT BY 1
      START WITH 1
      NOMAXVALUE
      NOCYCLE
      CACHE 10;

CREATE SEQUENCE SQ_DAILY_CAL_EXCEDEED
      INCREMENT BY 1
      START WITH 1
      NOMAXVALUE
      NOCYCLE
      CACHE 10;
