CREATE OR REPLACE TRIGGER TRG_INSERT_TB_STREAK
AFTER INSERT OR UPDATE ON TB_DAILY_CALORIES
FOR EACH ROW
DECLARE
V_CD_USER TB_STREAK.CD_USER%TYPE;
V_VL_STREAK TB_STREAK.VL_STREAK%TYPE;
BEGIN
	BEGIN
		SELECT TS.CD_USER
		INTO V_CD_USER
		FROM TB_STREAK TS
		WHERE TS.CD_USER = :NEW.CD_USER;

		EXCEPTION
	    WHEN NO_DATA_FOUND THEN  V_CD_USER := NULL;
	END;
		
	CASE WHEN V_CD_USER IS NOT NULL
	THEN
			SELECT TS.VL_STREAK
			INTO V_VL_STREAK
			FROM TB_STREAK TS
			WHERE TS.CD_USER = V_CD_USER;
			
			DBMS_OUTPUT.PUT_LINE(V_VL_STREAK);
			
		    UPDATE TB_STREAK
		    SET VL_STREAK = VL_STREAK + 1, DT_LAST_UPDATE = TRUNC(SYSDATE)
		    WHERE CD_USER = V_CD_USER;		
    ELSE
    		INSERT INTO TB_STREAK
			(CD_STREAK, VL_STREAK, CD_USER, DT_LAST_UPDATE)
			VALUES(SQ_CD_STREAK.nextval, 1, :NEW.CD_USER, TRUNC(SYSDATE));
    END CASE;
END;