--criar trigger para preencher last_update da tb_streak
CREATE OR REPLACE TRIGGER TRG_LAST_UPDATE_TB_STREAK
AFTER UPDATE OR INSERT  ON TB_STREAK
FOR EACH ROW
BEGIN
	DBMS_OUTPUT.PUT_LINE(:NEW.CD_USER);

    UPDATE TB_STREAK
	SET DT_LAST_UPDATE= TRUNC(SYSDATE)
	WHERE CD_USER= :NEW.CD_USER;
    
END;